// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ73c7jDIA5f_o7qX65eeGDXCSIpGn8TY',
    appId: '1:488580054038:web:2a479bcfb5b194e5c94937',
    messagingSenderId: '488580054038',
    projectId: 'pushnotification-2a132',
    authDomain: 'pushnotification-2a132.firebaseapp.com',
    storageBucket: 'pushnotification-2a132.appspot.com',
    measurementId: 'G-X4GJP8J9KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7SYZc_1j9nY2i2PJ_tRlkmgirLipF_Cw',
    appId: '1:488580054038:android:244265037758486ec94937',
    messagingSenderId: '488580054038',
    projectId: 'pushnotification-2a132',
    storageBucket: 'pushnotification-2a132.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlqCf_t5-fXHKanEvRQYLLLopjWYUpBfQ',
    appId: '1:488580054038:ios:a7e13c7e5a7a0d4ac94937',
    messagingSenderId: '488580054038',
    projectId: 'pushnotification-2a132',
    storageBucket: 'pushnotification-2a132.appspot.com',
    iosBundleId: 'com.example.demoApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlqCf_t5-fXHKanEvRQYLLLopjWYUpBfQ',
    appId: '1:488580054038:ios:979df42bfa37344ac94937',
    messagingSenderId: '488580054038',
    projectId: 'pushnotification-2a132',
    storageBucket: 'pushnotification-2a132.appspot.com',
    iosBundleId: 'com.example.demoApp1.RunnerTests',
  );
}
